# Generated by Django 4.1.2 on 2022-11-19 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='autho',
            new_name='author',
        ),
    ]
